name: bocal

services:
  bocal-smtpd:
    build: .
    container_name: bocal-smtpd
    ports:
      - "1025:1025"
    volumes:
      - ./dns/resolv.conf:/etc/resolv.conf:ro
    environment:
      - TLS_CERT_PATH=/app/certs/server.crt
      - TLS_KEY_PATH=/app/certs/server.key
    # dns:
    #   - 172.28.1.2 # Point to the coredns container's internal IP
    networks:
      bocal_net:
        ipv4_address: 172.28.1.1

  # Mock DNS server for SPF/DMARC/DKIM records
  coredns:
    image: coredns/coredns
    container_name: coredns
    command: -conf /etc/coredns/Corefile -dns.port 53
    ports:
      - "5354:53/udp"
    volumes:
      - ./dns/Corefile:/etc/coredns/Corefile
      - ./dns/zones:/etc/coredns/zones
    networks:
      bocal_net:
        ipv4_address: 172.28.1.2

  # Test email sender with DKIM signing capability
  bocal-email-sender:
    build:
      context: . # Build from the project root
      dockerfile: ./bocal-email-sender/Dockerfile
    container_name: bocal-email-sender
    volumes:
      - ./bocal-email-sender/keys/dkim.private:/app/keys/dkim.private:ro
    environment:
      - SMTP_SERVER=172.28.1.1
      - SMTP_PORT=1025
      - TLS_CERT_PATH=/app/certs/client.crt
      - TLS_KEY_PATH=/app/certs/client.key
    # dns:
    #   - 172.28.1.2 # Point to the coredns container's internal IP
    networks:
      bocal_net:
        ipv4_address: 172.28.1.3

networks:
  bocal_net:
    ipam:
      driver: default
      config:
        - subnet: 172.28.0.0/16
