FROM debian:bookworm-slim

RUN apt update && apt install -y curl jq unzip ca-certificates coreutils

RUN curl https://bws.bitwarden.com/install | sh
RUN export PATH="$PATH:/root/.local/bin"

COPY ./fetch-certs.sh /usr/local/bin/fetch-certs.sh
RUN chmod +x /usr/local/bin/fetch-certs.sh

# Set the entrypoint to be your script
ENTRYPOINT ["/usr/local/bin/fetch-certs.sh"]
CMD []
