name: bocal-smtpd

services:
  cert-fetcher:
    image: ${CERT_FETCHER_IMAGE_WITH_TAG}
    environment:
      - BWS_ACCESS_TOKEN
      - BWS_PROJECT_ID
      - BWS_PRIVATEKEY_ID
      - BWS_FULLCHAIN_ID
      - TLS_CERT_PATH=/app/certs/fullchain.pem
      - TLS_KEY_PATH=/app/certs/privatekey.pem
    volumes:
      - tls_certs_volume:/app/certs
      - ./cert-fetcher.sh:/usr/local/bin/cert-fetcher.sh:ro
    command: ["/usr/local/bin/cert-fetcher.sh"]

  bocal-smtpd:
    image: ${APP_IMAGE_WITH_TAG}
    restart: unless-stopped
    volumes:
      - tls_certs_volume:/app/certs:ro
    environment:
      - SMTP_SERVER_DOMAIN=mail.bocalusermail.fyi
      - DATABASE_URL
      - TLS_CERT_PATH=/app/certs/fullchain.pem
      - TLS_KEY_PATH=/app/certs/privatekey.pem
    depends_on:
      cert-fetcher:
        condition: service_completed_successfully
    networks:
      bocal_net:
    healthcheck:
      test: ["CMD-SHELL", "nc -z localhost 465 || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3

  haproxy:
    image: haproxy:latest
    volumes:
      - ./haproxy.prod.cfg:/usr/local/etc/haproxy/haproxy.cfg
    ports:
      - "587:587"
      - "465:465"
    networks:
      bocal_net:
    restart: unless-stopped

networks:
  bocal_net:
    ipam:
      driver: default
      config:
        - subnet: 172.28.0.0/16

volumes:
  tls_certs_volume:
