name: bocal

services:
  bocal-smtpd:
    build: .
    container_name: bocal-smtpd
    ports:
      - "1025:1025"
    volumes:
      - ./dns/resolv.conf:/etc/resolv.conf:ro
    environment:
      - TLS_CERT_PATH=/app/certs/server.crt
      - TLS_KEY_PATH=/app/certs/server.key
      - DATABASE_URL=postgres://admin:root@host.docker.internal:5432/bocal
    networks:
      bocal_net:
        ipv4_address: 172.28.1.1
    extra_hosts:
      - "host.docker.internal:host-gateway"

  # Mock DNS server for SPF/DMARC/DKIM records
  coredns:
    image: coredns/coredns
    container_name: coredns
    command: -conf /etc/coredns/Corefile -dns.port 53
    ports:
      - "5354:53/udp"
    volumes:
      - ./dns/Corefile:/etc/coredns/Corefile
      - ./dns/zones:/etc/coredns/zones
    networks:
      bocal_net:
        ipv4_address: 172.28.1.2

networks:
  bocal_net:
    ipam:
      driver: default
      config:
        - subnet: 172.28.0.0/16
