name: bocal_prod

services:
  bocal-smtpd:
    build:
      context: .
      target: prod
    ports:
      - "465:465"
    volumes:
      - certbot_data:/etc/secrets/letsencrypt:ro
    environment:
      # - TLS_CERT_PATH=/etc/secrets/letsencrypt/live/mail.yourdomain.com/fullchain.pem
      # - TLS_KEY_PATH=/etc/secrets/letsencrypt/live/mail.yourdomain.com/privkey.pem
      - DATABASE_URL=${DATABASE_URL}
    depends_on:
      certbot:
        condition: service_healthy
    networks:
      bocal_net_prod:
    healthcheck:
      # Basic healthcheck for TLS port.
      test: ["CMD-SHELL", "nc -z localhost 465 || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
    deploy:
      replicas: 3
      restart_policy:
        condition: unless-stopped

  caddy:
    build:
      context: .
      dockerfile: Dockerfile.caddy_l4
    image: bocal-caddy_l4/caddy-l4:latest
    ports:
      - "587:587"
      - "465:465"
    volumes:
      - caddy_data:/data
      - ./Caddyfile.prod:/etc/caddy/Caddyfile
    depends_on:
      - bocal-smtpd
    networks:
      bocal_net_prod:
    restart: unless-stopped

  # certbot:
  #   image: certbot/certbot
  #   command: certonly --webroot -w /var/www/certbot -d usermail.bocal.fyi --email root@bocal.fyi --agree-tos --noninteractive --force-renewal
  #   # Optional: Add command for renewal checks (e.g., a cron job wrapper)
  #   # command: /bin/sh -c "trap exit TERM; while :; do certbot renew; sleep 12h & wait $!; done;" # Example for continuous renewal checks
  #   volumes:
  #     - certbot_data:/etc/letsencrypt # Persistent storage for certs and config
  #     - webroot_volume:/var/www/certbot # Volume for webroot validation files
  #   environment:
  #     - CERTBOT_VERBOSITY=info
  #   networks:
  #     bocal_net_prod:
  #   deploy:
  #     restart_policy:
  #       condition: on-failure
  #   healthcheck:
  #     test:
  #       [
  #         "CMD-SHELL",
  #         "[ -f /etc/letsencrypt/live/usermail.bocal.fyi/fullchain.pem ]",
  #       ]
  #     interval: 30s
  #     timeout: 10s
  #     retries: 5

networks:
  bocal_net_prod:
    ipam:
      driver: default
      config:
        - subnet: 172.28.0.0/16
# volumes:
#   certbot_data:
#   webroot_volume:
